language: node_js
node_js:
  - "node"
cache: npm
script: npm run build
before_deploy:
  - npm run build
  - echo -e "node_modules\npackage-lock.json" > .gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
    